[[plugins]]
repo = 'rhysd/vim-crystal'
normalized_name = 'crystal'

[[plugins]]
repo = 'davidhalter/jedi-vim'
normalized_name = 'python-jedi'

[[plugins]]
repo = 'rust-lang/rust.vim'
normalized_name = 'rust'

[[plugins]]
repo = 'phildawes/racer'
normalized_name = 'rust-racer'
build = 'cargo build --release'

[[plugins]]
repo = 'rhysd/github-complete.vim'
normalized_name = 'github-complete'

[[plugins]]
repo = 'chrisbra/csv.vim'
normalized_name = 'csv'

