#===========
# lib
[[plugins]]
name = 'lib/dein'
repo = 'Shougo/dein.vim'

[[plugins]]
name = 'lib/vimproc'
repo = 'Shougo/vimproc.vim'
build = 'make'


#===========
# basic
[[plugins]]
name = 'basic/vimfiler'
repo = 'Shougo/vimfiler'

[[plugins]]
name = 'basic/vimref'
repo = 'thinca/vim-ref'

[[plugins]]
name = 'basic/vimshell'
repo = 'Shougo/vimshell'

[[plugins]]
name = 'basic/vinarise'
repo = 'Shougo/vinarise.vim'

[[plugins]]
name = 'basic/quickrun'
repo = 'thinca/vim-quickrun'


[[plugins]]
name = 'basic/neosnippet'
repo = 'Shougo/neosnippet'
depends = ['basic/neosnippet-snippets']
on_ft = 'snippet'
lazy = 1

[[plugins]]
name = 'basic/neosnippet-snippets'
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
name = 'basic/neoterm'
repo = 'cocuh/neoterm'
if = 'has("nvim")'

# # disable 2016/03/17, hang when in insert mode
#[[plugins]]
#name = 'basic/eskk'
#repo = 'tyru/eskk.vim'


#===========
# unite

[[plugins]]
name = 'unite/unite-build'
repo = 'Shougo/unite-build'

[[plugins]]
name = 'unite/unite'
repo = 'Shougo/unite.vim'


#===========
# compl
[[plugins]]
name = 'compl/deoplete'
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'

[[plugins]]
name = 'compl/neocomplete'
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'


#===========
# ui
[[plugins]]
name = 'ui/indent-guide'
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
name = 'ui/airline'
repo = 'vim-airline/vim-airline'


#===========
# lang
[[plugins]]
name = 'lang/crystal/ft'
repo = 'rhysd/vim-crystal'
on_ft = 'crystal'

[[plugins]]
name = 'lang/python/compl-jedi'
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
lazy = 1

[[plugins]]
name = 'lang/rust/ft'
repo = 'rust-lang/rust.vim'

[[plugins]]
name = 'lang/rust/compl-racer'
repo = 'racer-rust/vim-racer'

[[plugins]]
name = 'lang/markdown/compl-github'
repo = 'rhysd/github-complete.vim'
on_ft = 'markdown'
lazy = 1

[[plugins]]
name = 'lang/clang/compl'
repo = 'Rip-Rip/clang_complete'

[[plugins]]
name = 'lang/toml'
repo = 'cespare/vim-toml'

[[plugins]]
name = 'lang/vimscript/compl'
repo = 'Shougo/neco-vim'
on_i = 1
on_ft = 'vim'
lazy = 1

[[plugins]]
name = 'lang/elixir'
repo = 'elixir-lang/vim-elixir'

[[plugins]]
name = 'lang/vim-ansible-yaml'
repo = 'chase/vim-ansible-yaml'

